Repository clarisights/KnitUI, pull requests merged in 2019-09, with the labels that each got.

#70 Fix build errors + add customFontColor for inline labels
  .babelrc
  src/components/Label/InlineLabel.tsx
  src/components/Label/Label.stories.tsx
  src/components/Label/Label.tsx
  src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
  src/components/Label/commonUtils.ts
  src/components/Label/types.ts
  src/components/Modal/ModalWrapper.tsx
Labels: chore

#72 fix build
  .babelrc
  package.json
  yarn.lock
Labels: chore

#73 Fix padding overrides not working
  src/common/styles/GlobalStyles.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/ModalWrapper.tsx
  src/components/Modal/__tests__/Modal.test.tsx
  src/components/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/components/Modal/components/Header.tsx
  src/components/Modal/components/Main.tsx
  src/components/Modal/types.ts
Labels: bug

#78 Input component enhancements
  src/common/styles/variables.tsx
  src/common/types.ts
  src/components/Input/Input.README.md
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
  src/components/Input/README.md
  src/components/Input/__tests__/Input.test.tsx
  src/components/Input/__tests__/__snapshots__/Input.test.tsx.snap
Labels: enhancement

#79 Fix content overflow scenarios in modal
  src/common/styles/variables.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/ModalWrapper.tsx
  src/components/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/components/Modal/components/Footer.tsx
  src/components/Modal/components/Header.tsx
  src/components/Modal/components/Main.tsx
  src/components/Modal/variants/Base.tsx
  src/components/Modal/variants/BottomPanel.tsx
  src/components/Modal/variants/LeftPanel.tsx
  src/components/Modal/variants/RightPanel.tsx
  src/components/Modal/variants/interfaces.ts
  src/components/Modal/variants/styledComponents.ts
  src/components/Modal/variants/types.ts
Labels: bug
