Repository clarisights/KnitUI, pull requests merged in 2019-08, with the labels that each got.

#56 export GlobalStyles
  src/index.ts
Labels: chore

#55 Auto generate typescript definition file during build
  index.d.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: chore

#61 Remove default right alignment in Modal header's right section
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/components/Modal/components/Header.tsx
Labels: chore

#62 Fix style issues in the focus and active states of the button
  src/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
  src/components/Button/components/ButtonBase.tsx
Labels: bug

#63 Fix Animation of Modal
  src/components/Modal/ModalWrapper.tsx
  src/components/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
Labels: bug

#54 Added option for custom fill for part of some SVGs + story for showing all icons
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/Icons.tsx
Labels: chore, enhancement

#64 Modal: fix panel dimensions and add header variations
  src/common/styles/variables.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/ModalWrapper.tsx
  src/components/Modal/__tests__/Modal.test.tsx
  src/components/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/components/Modal/components/Header.tsx
  src/components/Modal/components/Main.tsx
  src/components/Modal/variants/LeftPanel.tsx
  src/components/Modal/variants/RightPanel.tsx
Labels: bug

#66 Icon: Modified size api
  src/components/Breadcrumb/Breadcrumb.stories.tsx
  src/components/Breadcrumb/__tests__/Breadcrumb.test.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/Icon.tsx
Labels: enhancement

#67 Adds inset variant in labels
  src/components/Label/Label.stories.tsx
  src/components/Label/Label.tsx
  src/components/Label/README.md
  src/components/Label/__tests__/Label.test.tsx
  src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
  src/components/Label/types.ts
Labels: enhancement

#68 Fix before psedo element applied to parent
  src/components/Label/Label.tsx
  src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
Labels: bug

#69 Add font color override api in label
  src/components/Label/Label.stories.tsx
  src/components/Label/Label.tsx
  src/components/Label/README.md
  src/components/Label/__tests__/Label.test.tsx
  src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
  src/components/Label/types.ts
Labels: enhancement
